# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Conari' do
  pod "RichEditorView"
  pod 'SDWebImage', '~>3.7'
end

target 'ConariUITests' do
  pod "RichEditorView"
  pod 'SDWebImage', '~>3.7'
end

target 'ConariUnitTests' do
  pod "RichEditorView"
  pod 'SDWebImage', '~>3.7' 
end

