platform :ios, '9.0'

target 'Conari' do
  use_frameworks!

  # Pods for Conari
  pod 'YouTubePlayer'
  pod "RichEditorView"
  pod 'SDWebImage', '~>3.7'
  pod 'Alamofire'
  
  # License Kit
  pod 'ESOpenSourceLicensesKit'
  post_install do |installer_representation|
    system("ruby Pods/ESOpenSourceLicensesKit/ESOpenSourceLicensesKit/Scripts/generate_licenses.rb --post_install")
  end

  target 'ConariUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConariUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
